# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/pengzhixiang/test/github/timer_github

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/pengzhixiang/test/github/timer_github

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running interactive CMake command-line interface..."
	/usr/bin/cmake -i .
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/pengzhixiang/test/github/timer_github/CMakeFiles /home/pengzhixiang/test/github/timer_github/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/pengzhixiang/test/github/timer_github/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named timertest

# Build rule for target.
timertest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 timertest
.PHONY : timertest

# fast build rule for target.
timertest/fast:
	$(MAKE) -f CMakeFiles/timertest.dir/build.make CMakeFiles/timertest.dir/build
.PHONY : timertest/fast

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/timertest.dir/build.make CMakeFiles/timertest.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/timertest.dir/build.make CMakeFiles/timertest.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/timertest.dir/build.make CMakeFiles/timertest.dir/main.cpp.s
.PHONY : main.cpp.s

task.o: task.cpp.o
.PHONY : task.o

# target to build an object file
task.cpp.o:
	$(MAKE) -f CMakeFiles/timertest.dir/build.make CMakeFiles/timertest.dir/task.cpp.o
.PHONY : task.cpp.o

task.i: task.cpp.i
.PHONY : task.i

# target to preprocess a source file
task.cpp.i:
	$(MAKE) -f CMakeFiles/timertest.dir/build.make CMakeFiles/timertest.dir/task.cpp.i
.PHONY : task.cpp.i

task.s: task.cpp.s
.PHONY : task.s

# target to generate assembly for a file
task.cpp.s:
	$(MAKE) -f CMakeFiles/timertest.dir/build.make CMakeFiles/timertest.dir/task.cpp.s
.PHONY : task.cpp.s

timer.o: timer.cpp.o
.PHONY : timer.o

# target to build an object file
timer.cpp.o:
	$(MAKE) -f CMakeFiles/timertest.dir/build.make CMakeFiles/timertest.dir/timer.cpp.o
.PHONY : timer.cpp.o

timer.i: timer.cpp.i
.PHONY : timer.i

# target to preprocess a source file
timer.cpp.i:
	$(MAKE) -f CMakeFiles/timertest.dir/build.make CMakeFiles/timertest.dir/timer.cpp.i
.PHONY : timer.cpp.i

timer.s: timer.cpp.s
.PHONY : timer.s

# target to generate assembly for a file
timer.cpp.s:
	$(MAKE) -f CMakeFiles/timertest.dir/build.make CMakeFiles/timertest.dir/timer.cpp.s
.PHONY : timer.cpp.s

wheel.o: wheel.cpp.o
.PHONY : wheel.o

# target to build an object file
wheel.cpp.o:
	$(MAKE) -f CMakeFiles/timertest.dir/build.make CMakeFiles/timertest.dir/wheel.cpp.o
.PHONY : wheel.cpp.o

wheel.i: wheel.cpp.i
.PHONY : wheel.i

# target to preprocess a source file
wheel.cpp.i:
	$(MAKE) -f CMakeFiles/timertest.dir/build.make CMakeFiles/timertest.dir/wheel.cpp.i
.PHONY : wheel.cpp.i

wheel.s: wheel.cpp.s
.PHONY : wheel.s

# target to generate assembly for a file
wheel.cpp.s:
	$(MAKE) -f CMakeFiles/timertest.dir/build.make CMakeFiles/timertest.dir/wheel.cpp.s
.PHONY : wheel.cpp.s

wheelnode.o: wheelnode.cpp.o
.PHONY : wheelnode.o

# target to build an object file
wheelnode.cpp.o:
	$(MAKE) -f CMakeFiles/timertest.dir/build.make CMakeFiles/timertest.dir/wheelnode.cpp.o
.PHONY : wheelnode.cpp.o

wheelnode.i: wheelnode.cpp.i
.PHONY : wheelnode.i

# target to preprocess a source file
wheelnode.cpp.i:
	$(MAKE) -f CMakeFiles/timertest.dir/build.make CMakeFiles/timertest.dir/wheelnode.cpp.i
.PHONY : wheelnode.cpp.i

wheelnode.s: wheelnode.cpp.s
.PHONY : wheelnode.s

# target to generate assembly for a file
wheelnode.cpp.s:
	$(MAKE) -f CMakeFiles/timertest.dir/build.make CMakeFiles/timertest.dir/wheelnode.cpp.s
.PHONY : wheelnode.cpp.s

wheeltimer.o: wheeltimer.cpp.o
.PHONY : wheeltimer.o

# target to build an object file
wheeltimer.cpp.o:
	$(MAKE) -f CMakeFiles/timertest.dir/build.make CMakeFiles/timertest.dir/wheeltimer.cpp.o
.PHONY : wheeltimer.cpp.o

wheeltimer.i: wheeltimer.cpp.i
.PHONY : wheeltimer.i

# target to preprocess a source file
wheeltimer.cpp.i:
	$(MAKE) -f CMakeFiles/timertest.dir/build.make CMakeFiles/timertest.dir/wheeltimer.cpp.i
.PHONY : wheeltimer.cpp.i

wheeltimer.s: wheeltimer.cpp.s
.PHONY : wheeltimer.s

# target to generate assembly for a file
wheeltimer.cpp.s:
	$(MAKE) -f CMakeFiles/timertest.dir/build.make CMakeFiles/timertest.dir/wheeltimer.cpp.s
.PHONY : wheeltimer.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... timertest"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... task.o"
	@echo "... task.i"
	@echo "... task.s"
	@echo "... timer.o"
	@echo "... timer.i"
	@echo "... timer.s"
	@echo "... wheel.o"
	@echo "... wheel.i"
	@echo "... wheel.s"
	@echo "... wheelnode.o"
	@echo "... wheelnode.i"
	@echo "... wheelnode.s"
	@echo "... wheeltimer.o"
	@echo "... wheeltimer.i"
	@echo "... wheeltimer.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

